spring:
  application:
    name:dhuGraduate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dhuGraduate
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#pagehelper的相关配置
pagehelper:
  reasonable: true
  helper-dialect: mysql

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    bucketName: java-dhu
    region: cn-shanghai